version: '3.8'

services:
  pg-manager:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - postgres-production
    privileged: true

  postgres-production:
    image: postgres:15
    environment:
      POSTGRES_DB: enigma
      POSTGRES_USER: enigma
      POSTGRES_PASSWORD: stonks123
    ports:
      - "5432:5432"
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: pg-manager-network
