apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-manager-config
data:
  config.json: |
    {
      "production": {
        "host": "localhost",
        "port": 5432,
        "user": "postgres",
        "password": "",
        "database": "production_db",
        "ssl_mode": "disable"
      },
      "backups": [
        {
          "id": "backup1",
          "host": "localhost",
          "port": 5433,
          "user": "postgres",
          "password": "",
          "database": "backup_db1",
          "ssl_mode": "disable",
          "priority": 1,
          "active": true,
          "auto_create": true,
          "docker_image": "postgres:15"
        },
        {
          "id": "backup2",
          "host": "localhost",
          "port": 5434,
          "user": "postgres",
          "password": "",
          "database": "backup_db2",
          "ssl_mode": "disable",
          "priority": 2,
          "active": true,
          "auto_create": true,
          "docker_image": "postgres:15"
        }
      ],
      "server": {
        "port": 8080
      },
      "replication": {
        "batch_size": 1000,
        "worker_count": 10,
        "flush_interval": "5s",
        "max_retries": 3,
        "health_check_interval": "30s"
      },
      "docker": {
        "network": "pg-manager-network",
        "data_path": "./data"
      }
    }
