apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-manager
  labels:
    app: pg-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pg-manager
  template:
    metadata:
      labels:
        app: pg-manager
    spec:
      containers:
      - name: pg-manager
        image: pg-manager:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /app/config
        env:
        - name: LOG_LEVEL
          value: "info"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: pg-manager-config
---
apiVersion: v1
kind: Service
metadata:
  name: pg-manager-service
spec:
  selector:
    app: pg-manager
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
