apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "production"
        - name: POSTGRES_USER
          value: "replicator"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - replicator
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - replicator
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-service
spec:
  selector:
    app: postgres-primary
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-backup1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backup1
  template:
    metadata:
      labels:
        app: postgres-backup1
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "backup"
        - name: POSTGRES_USER
          value: "replicator"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-backup1-service
spec:
  selector:
    app: postgres-backup1
  ports:
  - port: 5432
    targetPort: 5432
